# Generated by Django 5.0.6 on 2024-07-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0003_alter_studentfees_total_fees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentfees",
            name="date_paid",
        ),
        migrations.RemoveField(
            model_name="studentfees",
            name="total_fees",
        ),
        migrations.AlterField(
            model_name="studentfees",
            name="paid_fees",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="studentfees",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentfees",
                to="student_management_app.students",
            ),
        ),
    ]
